[package]
name = "elfloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cpio_reader = "0.1.1"
xmas-elf = "0.7.0"